# Site settings
baseurl = "https://brianketelsen.com"
title = "Brian Ketelsen"
paginate = 5
canonifyurls = false
buildFuture = true
theme = "bjk"
googleAnalytics = "UA-46945124-1"
copyright = "Brian Ketelsen"

[params]
  # dir name of your blog content (default is `content/posts`)
  contentTypeName = "posts"
  # ["orange", "blue", "red", "green", "pink"]
  themeColor = "blue"
  # if you set this to 0, only submenu trigger will be visible
  showMenuItems = 2
  author = "Brian Ketelsen"
  twitter = "bketelsen"
  tagline = "Sniffing the Glue"
  
[menu]
  [[menu.nav]]
  name = "Posts"
  url = "/"
  weight = 1
  [[menu.nav]]
  name = "Projects"
  url = "/projects"
  weight = 2
  [[menu.nav]]
  name = "Topics"
  url = "/tags/"
  weight = 3
  [[menu.nav]]
  name = "About"
  url = "/about/"
  weight = 4
  [[menu.nav]]
  name = "RSS"
  url = "/index.xml"
  weight = 5

[outputs]
  home = ["HTML", "JSON", "RSS"]
  page = ["HTML"]
  section = ["HTML", "RSS"]
  taxonomy = ["HTML", "RSS"]
  taxonomyTerm = ["HTML", "RSS"]