# For a description of these parameters, please visit the theme wiki.
# https://github.com/pacollins/hugo-future-imperfect-slim/wiki/config.toml
baseurl                 = "https://brianketelsen.com/"
DefaultContentLanguage  = "en"
title                   = "Brian Ketelsen"
theme                   = "future"
paginate                = 3
disqusShortname         = ""
googleAnalytics         = "UA-46945124-1"
pluralizeListTitles     = false
disableLanguages        = [""]

[outputs]
  home                  = ["html", "json"]

[params]
  enableCDN             = false
  cssFiles              = ["default"]
  jsFiles               = ["default"]
  highlightjs           = true
  highlightjsTheme      = "github"
  highlightjsLang       = ["html", "css", "js", "toml","rust","go"]
  viewMorePostsLink     = "/blog/"
  readingTime           = true
  socialShare           = ["twitter", "reddit", "linkedin",  "email"]

  [params.meta]
    description         = "Cloud Development, Open Source, Distributed Computing."
    author              = "Brian Ketelsen"
    favicon             = false
    svg                 = true
    faviconVersion      = "1"
    msColor             = "#ffffff"
    iOSColor            = "#ffffff"

  [params.header]
    navbarTitle         = "Brian Ketelsen"
    dynamicTitles       = true
    searchMenu          = true
    shareMenu           = true
    languageMenu        = false

  [params.intro]
    header                = "Brian Ketelsen"
    paragraph             = "I'm a cloud advocate focused on the future of distributed computing."
    rssIntro              = true
    socialIntro           = true
    hideWhenSingleColumn  = true
    alwaysOnHomepage      = false

    [params.intro.pic]
      src                 = "img/main/bri.png"
      shape               = "circle"
      width               = "81"
      alt                 = "Brian Ketelsen"

  [params.sidebar]
    about               = "Hard to believe this content is free."
    postAmount          = 5
    categories          = true
    categoriesByCount   = true

  [params.footer]
    rssFooter           = true
    socialFooter        = true

  [params.staticman]
    enabled             = false
    api                 = ""  # No Trailing Slash
    gitProvider         = ""
    username            = ""
    repo                = ""
    branch              = ""

    [params.staticman.recaptcha]
      siteKey           = ""
      encryptedKey      = ""

[menu]

  [[menu.main]]
    name              = "Home"
    identifier        = "home"
    url               = "/"
    pre               = "<i class='fa fa-home'></i>"
    weight            = 1

  [[menu.main]]
    name              = "About"
    identifier        = "about"
    url               = "/about/"
    pre               = "<i class='far fa-id-card'></i>"
    weight            = 2

  [[menu.main]]
    name              = "Blog"
    identifier        = "blog"
    url               = "/blog/"
    pre               = "<i class='far fa-newspaper'></i>"
    weight            = 3

  [[menu.main]]
    name              = "Projects"
    identifier        = "projects"
    url               = "/projects/"
    pre               = "<i class='fas fa-microchip'></i>"
    weight            = 5
  
  [[menu.main]]
    name              = "Quick"
    identifier        = "quick"
    url               = "/quick/"
    pre               = "<i class='fas fa-fighter-jet'></i>"
    weight            = 6

  [[menu.main]]
    name              = "LPT"
    identifier        = "lpt"
    url               = "/lpt/"
    pre               = "<i class='fas fa-lightbulb'></i>"
    weight            = 7
  
  [[menu.main]]
    name              = "Categories"
    identifier        = "categories"
    url               = "/categories/"
    pre               = "<i class='fas fa-sitemap'></i>"
    weight            = 8

[Languages]

  [Languages.en]
    LanguageCode        = "en"
    LanguageName        = "English"
    weight              = 1

[social]
  # Coding Communities
  github                = "bketelsen"
  gitlab                = ""
  stackoverflow         = "" # User Number
  bitbucket             = ""
  jsfiddle              = ""
  codepen               = ""
  # Visual Art Communities
  deviantart            = ""
  flickr                = ""
  behance               = ""
  dribbble              = ""
  # Publishing Communities
  wordpress             = ""
  medium                = ""
  # Professional/Business Oriented Communities
  linkedin              = "bketelsen"
  linkedin_company      = ""
  foursquare            = ""
  xing                  = ""
  slideshare            = ""
  # Social Networks
  facebook              = ""
  googleplus            = ""
  reddit                = "brianketelsen"
  quora                 = ""
  youtube               = "bketelsen"
  twitch                = "bketelsen"
  vimeo                 = ""
  whatsapp              = "" # WhatsApp Number
    # WeChat and QQ need testing.
    wechat              = ""
    qq                  = "" # User ID Number
  instagram             = ""
  tumblr                = ""
  twitter               = "bketelsen"
  strava                = ""
  skype                 = ""
  snapchat              = ""
  pinterest             = ""
  telegram              = ""
  vine                  = ""
  googlescholar         = ""
  orcid                 = ""
  researchgate          = ""
  keybase               = "bketelsen"
  mastodon              = ""
  # Email
  email                 = "mail@bjk.fyi"
