# Site settings
theme = "story"
baseurl = "https://brianketelsen.com/"
title = "Sniffing the Glue"
paginate = 5
buildFuture = true
googleAnalytics = "UA-46945124-1"

[[menu.social]]
  name = "GitHub"
  title = "fab fa-github-square"
  url = "https://github.com/bketelsen"

[[menu.main]]
  name = "Quick"
  title = "Quick"
  url = "/quick/"

[[menu.main]]
  name = "Posts"
  title = "Posts"
  url = "/posts/"

[[menu.main]]
  name = "Talks"
  title = "Talks"
  url = "/talks/"

[[menu.main]]
  name = "Slides"
  title = "Slides"
  url = "/slides/"

[[menu.main]]
  name = "Projects"
  title = "Projects"
  url = "/projects/"

[params]
  author = "Brian Ketelsen"
  twitter = "bketelsen"
  classes = []

[outputs]
  home = ["HTML", "JSON", "RSS"]
  page = ["HTML"]
  section = ["HTML", "RSS"]
  taxonomy = ["HTML", "RSS"]
  taxonomyTerm = ["HTML", "RSS"]
